# Generated by Django 3.2 on 2025-12-22 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('city_country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority', 'airport_code'],
            },
        ),
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('flight_search_type', models.CharField(choices=[('Oneway', 'One-way'), ('Return', 'Return')], max_length=10)),
                ('ticket_class', models.CharField(default='Y', max_length=10)),
                ('adults', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('infants', models.IntegerField(default=0)),
                ('departure_code', models.CharField(max_length=10)),
                ('destination_code', models.CharField(max_length=10)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=100)),
                ('connection_id', models.CharField(max_length=100)),
                ('connection_code', models.CharField(max_length=100)),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_currency', models.CharField(default='NGN', max_length=10)),
                ('airline_code', models.CharField(max_length=10)),
                ('airline_name', models.CharField(max_length=200)),
                ('departure_code', models.CharField(max_length=10)),
                ('departure_name', models.CharField(max_length=200)),
                ('departure_time', models.DateTimeField()),
                ('arrival_code', models.CharField(max_length=10)),
                ('arrival_name', models.CharField(max_length=200)),
                ('arrival_time', models.DateTimeField()),
                ('stops', models.IntegerField(default=0)),
                ('trip_duration', models.CharField(max_length=50)),
                ('is_refundable', models.BooleanField(default=False)),
                ('flight_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='flights.flightsearch')),
            ],
            options={
                'ordering': ['price_amount'],
            },
        ),
        migrations.CreateModel(
            name='FlightLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_number', models.IntegerField()),
                ('departure_code', models.CharField(max_length=10)),
                ('departure_name', models.CharField(max_length=200)),
                ('destination_code', models.CharField(max_length=10)),
                ('destination_name', models.CharField(max_length=200)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(max_length=50)),
                ('is_stop', models.BooleanField(default=False)),
                ('layover', models.CharField(blank=True, max_length=100, null=True)),
                ('cabin_class', models.CharField(max_length=10)),
                ('cabin_class_name', models.CharField(max_length=100)),
                ('operating_carrier', models.CharField(max_length=10)),
                ('marketing_carrier', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=20)),
                ('flight_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='flights.flightresult')),
            ],
            options={
                'ordering': ['leg_number'],
            },
        ),
    ]
