# Generated by Django 3.2 on 2025-12-22 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('trip_type', models.CharField(choices=[('One-way', 'One-way'), ('Return', 'Return'), ('Multi-City', 'Multi-City')], max_length=20)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('pnr', models.CharField(blank=True, max_length=20, null=True)),
                ('pnr_status', models.CharField(blank=True, choices=[('Issued', 'Issued'), ('—', '—')], max_length=20, null=True)),
                ('reissue_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reissue_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='flights.flightresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('nin', models.CharField(blank=True, max_length=50, null=True)),
                ('bvn', models.CharField(blank=True, max_length=50, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='bookings.booking')),
            ],
        ),
    ]
